# Azure Pipelines YAML pipeline.
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
name: ninja

trigger:
- flutter-*-tizen
pr:
- flutter-*-tizen

jobs:
- job: format
  pool:
    name: Default
    demands: agent.os -equals Linux
  steps:
  - checkout: self
    path: src/flutter
  - bash: |
      gclient sync -f -D
      sed -i 's/"-Wno-non-c-typedef-for-linkage",//g' build/config/compiler/BUILD.gn
      sed -i 's/"-Wno-psabi",//g' build/config/compiler/BUILD.gn
      sed -i 's/defined(__ELF__) && defined(__GNUC__)/0/g' third_party/boringssl/src/crypto/mem.c
    displayName: Run gclient sync
    workingDirectory: $(Pipeline.Workspace)/src
    failOnStderr: true
  - bash: ci/format.sh
    displayName: Verify formatting
- job: build
  dependsOn: format
  strategy:
    matrix:
      tizen-arm-release:
        arch: arm
        mode: release
        targetTriple: armv7l-tizen-linux-gnueabi
      tizen-arm-profile:
        arch: arm
        mode: profile
        targetTriple: armv7l-tizen-linux-gnueabi
      tizen-arm-debug:
        arch: arm
        mode: debug
        targetTriple: armv7l-tizen-linux-gnueabi
      tizen-arm64-release:
        arch: arm64
        mode: release
        targetTriple: aarch64-tizen-linux-gnu
      tizen-arm64-profile:
        arch: arm64
        mode: profile
        targetTriple: aarch64-tizen-linux-gnu
      tizen-arm64-debug:
        arch: arm64
        mode: debug
        targetTriple: aarch64-tizen-linux-gnu
      tizen-x86-debug:
        arch: x86
        mode: debug
        targetTriple: i586-tizen-linux-gnueabi
  pool:
    name: Default
    demands: agent.os -equals Linux
  timeoutInMinutes: 60
  cancelTimeoutInMinutes: 1
  steps:
  - checkout: self
    path: src/flutter
  - bash: |
      flutter/tools/gn \
        --target-os linux \
        --linux-cpu $(arch) \
        --target-toolchain $HOME/tizen_tools/toolchains \
        --target-sysroot $HOME/tizen_tools/sysroot/$(arch) \
        --target-triple $(targetTriple) \
        --runtime-mode $(mode) \
        --enable-fontconfig \
        --embedder-for-target \
        --disable-desktop-embeddings \
        --build-tizen-shell
      ninja -C out/linux_$(mode)_$(arch)
    displayName: Build
    workingDirectory: $(Pipeline.Workspace)/src
    failOnStderr: true
  - bash: |
      OUTDIR=$(Build.StagingDirectory)
      cp out/linux_$(mode)_$(arch)/libflutter_*.so $OUTDIR
      if [[ $(System.JobName) == "tizen-arm-release" ]]; then
        mkdir $OUTDIR/common
        cp -r out/linux_$(mode)_$(arch)/{cpp_client_wrapper,icu,public} $OUTDIR/common
        rm $OUTDIR/common/cpp_client_wrapper/engine_method_result.cc
      fi
    displayName: Copy artifacts
    workingDirectory: $(Pipeline.Workspace)/src
    failOnStderr: true
  - publish: $(Build.StagingDirectory)
    artifact: $(System.JobName)
- job: release
  dependsOn: build
  pool:
    name: Default
    demands: agent.os -equals Linux
  workspace:
    clean: outputs
  variables:
  - name: upstreamVersion
    value: 0fdb562ac8068ce3dda6b69aca3f355f4d1d2718
  steps:
  - checkout: self
    path: src/flutter
  - download: current
  - bash: |
      mv $(Pipeline.Workspace)/tizen-arm-release/common .
      mv $(Pipeline.Workspace)/tizen-* .
      for platform in linux windows darwin; do
        for arch in arm arm64; do
          for mode in release profile; do
            curl -o tmp.zip https://storage.googleapis.com/flutter_infra/flutter/$(upstreamVersion)/android-$arch-$mode/$platform-x64.zip 2> /dev/null
            unzip tmp.zip -d tizen-$arch-$mode/$platform-x64 && rm tmp.zip
          done
          zip -r $(Build.StagingDirectory)/$platform-x64.zip *
          rm -r tizen-$arch-*/$platform-x64
        done
      done
    displayName: Create releases
    workingDirectory: $(Build.BinariesDirectory)
    failOnStderr: true
  - publish: $(Build.StagingDirectory)
    artifact: release
